sudo: false
language: node_js
node_js:
  - "0.10"
before_install: npm install -g grunt-cli
env:
  global:
    - secure: EpYkviZ1vRrXesZp221s0boZnhaQCLNcj0nX0p8shLH9wgR94Alc57THAp5g+1n3rziY/FrezI5jSr8J+6u3lNqOdkfsZ+zvzBQAOgtCKg7o8I4b0o0C/xLg1+dxoVTjEdXZhi1QskHzrNBvtZraSX6fW+XTaT3/hi5lwnpq04k=
    - secure: U1xFgm37PbYC9H8g4J9uWSHHxqvv/0AluL+4muJ6H9d8HaQV34WUTR6iRBusWn34Zc5m/aVeCreMInobknbM/9El66Q5B3tMHj7qMudrVGAyzrC6oaTYp4RtJexQ3XFJ0qCe79/wHWcJ+NWkIzToX5renuuME7ULMIzcPqDGIPg=
